// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockLedgerRetail.EntityFrameworkCore;

#nullable disable

namespace StockLedgerRetail.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(StockLedgerRetailDbContext))]
    partial class StockLedgerRetailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.BackgroundJobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("JobKey", "StartedAtUtc");

                    b.ToTable("background_job_runs", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.BackgroundJobSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastRunCompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastRunStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobKey")
                        .IsUnique();

                    b.ToTable("background_job_settings", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.CurrentStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LastTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityAvailable")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityReserved")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LastTransactionId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ProductVariantId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("current_stocks", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GrNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("InventoryDocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrNo")
                        .IsUnique();

                    b.HasIndex("InventoryDocumentId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("goods_receipts", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uuid");

                    b.Property<string>("LotCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderLineId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("PurchaseOrderLineId");

                    b.ToTable("goods_receipt_lines", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GoodsReceiptLineBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("GoodsReceiptLineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("GoodsReceiptLineId");

                    b.ToTable("goods_receipt_line_barcodes", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GroupPermission", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("group_permissions", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InsightSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InsightKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SnapshotKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotKey")
                        .IsUnique();

                    b.HasIndex("InsightKind", "GeneratedAtUtc");

                    b.ToTable("insight_snapshots", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CompletedApprovalSteps")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DestinationWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DocumentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstApprovedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("InTransitWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RequiredApprovalSteps")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("SourceWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("text");

                    b.Property<int>("TransferLifecycleStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWarehouseId");

                    b.HasIndex("DocumentNo")
                        .IsUnique();

                    b.HasIndex("InTransitWarehouseId");

                    b.HasIndex("SourceWarehouseId");

                    b.HasIndex("SourceSystem", "ReferenceNo", "DocumentType")
                        .IsUnique()
                        .HasFilter("\"ReferenceNo\" IS NOT NULL AND \"SourceSystem\" IS NOT NULL");

                    b.ToTable("inventory_documents", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryDocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("StockLotId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("StockLotId");

                    b.ToTable("inventory_document_lines", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryDocumentLineBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("InventoryDocumentLineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("InventoryDocumentLineId");

                    b.ToTable("inventory_document_line_barcodes", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryValuationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AverageCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("InventoryValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityAvailable")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("QuantityReserved")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ValuationMethod")
                        .HasColumnType("integer");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "SnapshotDate");

                    b.HasIndex("ProductVariantId", "WarehouseId", "SnapshotDate")
                        .IsUnique();

                    b.ToTable("inventory_valuation_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_inventory_valuation_snapshots_available_non_negative", "\"QuantityAvailable\" >= 0");

                            t.HasCheckConstraint("CK_inventory_valuation_snapshots_on_hand_non_negative", "\"QuantityOnHand\" >= 0");

                            t.HasCheckConstraint("CK_inventory_valuation_snapshots_reserved_non_negative", "\"QuantityReserved\" >= 0");

                            t.HasCheckConstraint("CK_inventory_valuation_snapshots_value_non_negative", "\"InventoryValue\" >= 0");
                        });
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.LotStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("StockLotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("StockLotId", "WarehouseId")
                        .IsUnique();

                    b.ToTable("lot_stocks", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.MarkdownPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowBelowCost")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LookbackDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxMarkdownPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<int>("MinDaysWithoutOutbound")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinGrossMarginPercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal?>("MinInventoryValueAtCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MinOnHand")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("RequireApprovalAbovePercent")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<decimal>("SlowSellThroughThreshold")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("TiersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("WarehouseType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId", "RegionCode", "WarehouseType", "IsActive");

                    b.ToTable("markdown_policies", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PermissionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission_groups", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.ProductCostHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("CostSource")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ValuationMethod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ProductVariantId", "EffectiveFrom");

                    b.HasIndex("ProductVariantId", "IsCurrent");

                    b.ToTable("product_cost_histories", null, t =>
                        {
                            t.HasCheckConstraint("CK_product_cost_history_cost_price_non_negative", "\"CostPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceAfterVat")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("PriceBeforeVat")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("PriceType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ProductVariantId", "EffectiveFrom");

                    b.HasIndex("ProductVariantId", "IsCurrent");

                    b.ToTable("product_prices", null, t =>
                        {
                            t.HasCheckConstraint("CK_product_prices_after_vat_non_negative", "\"PriceAfterVat\" >= 0");

                            t.HasCheckConstraint("CK_product_prices_before_vat_non_negative", "\"PriceBeforeVat\" >= 0");

                            t.HasCheckConstraint("CK_product_prices_vat_rate_non_negative", "\"VatRate\" >= 0");
                        });
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("CostPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("CostSource")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CurrentCostEffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentCostPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("CurrentCostSource")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CurrentPriceEffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CurrentSellingPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("CurrentSellingPriceAfterVat")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("CurrentSellingPriceBeforeVat")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("IsBarcode")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Season")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("SellingPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("TrackLotExpiry")
                        .HasColumnType("boolean");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("VatRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("BrandId", "Sku")
                        .IsUnique();

                    b.ToTable("product_variants", null, t =>
                        {
                            t.HasCheckConstraint("CK_product_variants_cost_price_non_negative", "\"CostPrice\" IS NULL OR \"CostPrice\" >= 0");

                            t.HasCheckConstraint("CK_product_variants_current_cost_price_non_negative", "\"CurrentCostPrice\" IS NULL OR \"CurrentCostPrice\" >= 0");

                            t.HasCheckConstraint("CK_product_variants_current_selling_price_non_negative", "\"CurrentSellingPrice\" IS NULL OR \"CurrentSellingPrice\" >= 0");

                            t.HasCheckConstraint("CK_product_variants_selling_price_non_negative", "\"SellingPrice\" IS NULL OR \"SellingPrice\" >= 0");

                            t.HasCheckConstraint("CK_product_variants_vat_rate_non_negative", "\"VatRate\" IS NULL OR \"VatRate\" >= 0");
                        });
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedApprovalSteps")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ExpectedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstApprovedBy")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PoNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RequiredApprovalSteps")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PoNo")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SupplierId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("purchase_orders", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("OrderedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("purchase_order_lines", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PurchaseOrderLineBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PurchaseOrderLineId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("PurchaseOrderLineId");

                    b.ToTable("purchase_order_line_barcodes", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LotCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("ManufacturedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId", "LotCode")
                        .IsUnique();

                    b.ToTable("stock_lots", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReferenceKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReservationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReservationNo")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.HasIndex("SourceSystem", "ReferenceType", "ReferenceKey", "WarehouseId", "Status");

                    b.ToTable("stock_reservations", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockReservationLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("StockReservationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("StockReservationId", "ProductVariantId")
                        .IsUnique();

                    b.ToTable("stock_reservation_lines", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AfterQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("BeforeQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("CounterpartWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentLineId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CounterpartWarehouseId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("DocumentLineId");

                    b.HasIndex("DocumentNo");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("TransactionDate");

                    b.HasIndex("TransactionNo")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("stock_transactions", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockTransactionBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StockTransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("StockTransactionId");

                    b.ToTable("stock_transaction_barcodes", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LeaderUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LeaderUserId");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.TransactionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityId");

                    b.HasIndex("EntityName");

                    b.HasIndex("Action", "CreatedAt");

                    b.HasIndex("CreatedBy", "CreatedAt");

                    b.HasIndex("EntityName", "CreatedAt");

                    b.ToTable("transaction_logs", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.TransferPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowCrossBrand")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("DestinationBrandId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("SourceBrandId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationBrandId");

                    b.HasIndex("SourceBrandId", "DestinationBrandId", "IsActive");

                    b.ToTable("transfer_policies", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.UserGroupAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("user_group_assignments", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.UserWarehouseAssignment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.HasKey("UserId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("UserId", "IsPrimary");

                    b.ToTable("user_warehouse_assignments", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.VariantUnitBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ProductVariantId", "WarehouseId", "Status");

                    b.ToTable("variant_unit_barcodes", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FulfillmentPriority")
                        .HasColumnType("integer");

                    b.Property<string>("FullAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentWarehouseId");

                    b.HasIndex("Type", "BrandId");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.CurrentStock", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.StockTransaction", "LastTransaction")
                        .WithMany("CurrentStocks")
                        .HasForeignKey("LastTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("CurrentStocks")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("CurrentStocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LastTransaction");

                    b.Navigation("ProductVariant");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GoodsReceipt", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.InventoryDocument", "InventoryDocument")
                        .WithMany()
                        .HasForeignKey("InventoryDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockLedgerRetail.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryDocument");

                    b.Navigation("PurchaseOrder");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Lines")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");

                    b.Navigation("ProductVariant");

                    b.Navigation("PurchaseOrderLine");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GoodsReceiptLineBarcode", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.GoodsReceiptLine", "GoodsReceiptLine")
                        .WithMany("UnitBarcodes")
                        .HasForeignKey("GoodsReceiptLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsReceiptLine");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GroupPermission", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.PermissionGroup", "Group")
                        .WithMany("Permissions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.Permission", "Permission")
                        .WithMany("Groups")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryDocument", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "DestinationWarehouse")
                        .WithMany()
                        .HasForeignKey("DestinationWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "InTransitWarehouse")
                        .WithMany()
                        .HasForeignKey("InTransitWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "SourceWarehouse")
                        .WithMany()
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DestinationWarehouse");

                    b.Navigation("InTransitWarehouse");

                    b.Navigation("SourceWarehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryDocumentLine", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.InventoryDocument", "Document")
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("InventoryDocumentLines")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.StockLot", "StockLot")
                        .WithMany()
                        .HasForeignKey("StockLotId");

                    b.Navigation("Document");

                    b.Navigation("ProductVariant");

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryDocumentLineBarcode", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.InventoryDocumentLine", "Line")
                        .WithMany("UnitBarcodes")
                        .HasForeignKey("InventoryDocumentLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryValuationSnapshot", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("ValuationSnapshots")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.LotStock", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.StockLot", "StockLot")
                        .WithMany("LotStocks")
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockLot");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.MarkdownPolicy", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Product", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Brand", "BrandEntity")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BrandEntity");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.ProductCostHistory", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("CostHistory")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.ProductPrice", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("PriceHistory")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PurchaseOrderLineBarcode", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.PurchaseOrderLine", "PurchaseOrderLine")
                        .WithMany("UnitBarcodes")
                        .HasForeignKey("PurchaseOrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrderLine");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockLot", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockReservation", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockReservationLine", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.StockReservation", "StockReservation")
                        .WithMany("Lines")
                        .HasForeignKey("StockReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("StockReservation");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockTransaction", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "CounterpartWarehouse")
                        .WithMany()
                        .HasForeignKey("CounterpartWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockLedgerRetail.Domain.Entities.InventoryDocument", "Document")
                        .WithMany("StockTransactions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.InventoryDocumentLine", "DocumentLine")
                        .WithMany("StockTransactions")
                        .HasForeignKey("DocumentLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("StockTransactions")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CounterpartWarehouse");

                    b.Navigation("Document");

                    b.Navigation("DocumentLine");

                    b.Navigation("ProductVariant");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockTransactionBarcode", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.StockTransaction", "StockTransaction")
                        .WithMany("Barcodes")
                        .HasForeignKey("StockTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockTransaction");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Team", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.AppUser", "Leader")
                        .WithMany("LedTeams")
                        .HasForeignKey("LeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.AppUser", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.TransferPolicy", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Brand", "DestinationBrand")
                        .WithMany()
                        .HasForeignKey("DestinationBrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockLedgerRetail.Domain.Entities.Brand", "SourceBrand")
                        .WithMany()
                        .HasForeignKey("SourceBrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DestinationBrand");

                    b.Navigation("SourceBrand");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.UserGroupAssignment", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.PermissionGroup", "Group")
                        .WithMany("UserAssignments")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.AppUser", "User")
                        .WithMany("GroupAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.UserWarehouseAssignment", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.AppUser", "User")
                        .WithMany("WarehouseAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.VariantUnitBarcode", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProductVariant");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Warehouse", b =>
                {
                    b.HasOne("StockLedgerRetail.Domain.Entities.Brand", "Brand")
                        .WithMany("Warehouses")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockLedgerRetail.Domain.Entities.Warehouse", "ParentWarehouse")
                        .WithMany("ChildWarehouses")
                        .HasForeignKey("ParentWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Brand");

                    b.Navigation("ParentWarehouse");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("GroupAssignments");

                    b.Navigation("LedTeams");

                    b.Navigation("TeamMemberships");

                    b.Navigation("WarehouseAssignments");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.GoodsReceiptLine", b =>
                {
                    b.Navigation("UnitBarcodes");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryDocument", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.InventoryDocumentLine", b =>
                {
                    b.Navigation("StockTransactions");

                    b.Navigation("UnitBarcodes");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Permission", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PermissionGroup", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Product", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.ProductVariant", b =>
                {
                    b.Navigation("CostHistory");

                    b.Navigation("CurrentStocks");

                    b.Navigation("InventoryDocumentLines");

                    b.Navigation("PriceHistory");

                    b.Navigation("StockTransactions");

                    b.Navigation("ValuationSnapshots");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.PurchaseOrderLine", b =>
                {
                    b.Navigation("UnitBarcodes");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockLot", b =>
                {
                    b.Navigation("LotStocks");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockReservation", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.StockTransaction", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("CurrentStocks");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("StockLedgerRetail.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("ChildWarehouses");

                    b.Navigation("CurrentStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
